name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: create Virtual env
      run: make venv_create
    - name: run tests
      run: |
        source .venv/bin/activate
        make coverage-ci
    - name: Upload code coverage report to Codecov.io
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  build-and-push:
    name: podman build from Dockerfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Podman
        run: |
          sudo apt-get update
          sudo apt-get install podman

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: distributors-backend
          tags: ${{ github.sha }}
          containerfiles: ./Dockerfile

      - name: Push Image
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: distributors-backend
          tags: ${{ github.sha }}
          registry: quay.io/cloudservices
